### ISSUE TITLE
Uncompatible with latest version again. 

### ISSUE THREAD

**Issue by tersian** [lsegal/atom-rst-preview#44] opened 2016-11-21 04:46 UTC
npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/xxxx/.atom/.apm/.apmrc" "--userconfig" "/Users/xxxx/.atom/.apmrc" "rebuild" "--runtime=electron" "--target=1.3.9" "--arch=x64"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh
npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/xxxx/.atom/.apm/.apmrc" "--userconfig" "/Users/xxx/.atom/.apmrc" "rebuild" "--runtime=electron" "--target=1.3.9" "--arch=x64"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.1 install: `node-gyp rebuild`
npm ERR! Exit status -2
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxx/.atom/packages/rst-preview/npm-debug.log

**Comment by apeltzer** [comment] 2016-11-22 14:22
I can unfortunately confirm this behaviour - this does not work anymore, same error as above.

**Comment by tersian** [comment] 2016-11-22 15:46
I completely removed atom and all of it's configuration from my Mac, then re-installed it from the website and got rst-preview to work. I think the upgrade of my Mac to Sierra and the atom upgrades did something bad to node.js or npm and a full re-install fixed it. Just a theory.

**Comment by wmayner** [comment] 2016-11-28 20:19
Confirmed. Cannot reproduce @tersian's fix.

**Comment by apeltzer** [comment] 2016-11-28 20:47
For me recompiling the extension worked - atom figured out that the atom-rst-preview extension was built using an older version and asked me to recompile. After that, it worked again.

**Comment by lsegal** [comment] 2016-11-29 04:42
This seems like an OS issue. Re-compiling your binaries should fix this (since it relies on platform-dependent native modules). Thanks for the input, everyone. Closing this.

**Closed as completed by lsegal** 2016-11-29 04:42 UTC

**Comment by tersian** [comment] 2016-11-29 04:48
I tried re-compiling and it was unsuccessful. That's why I had to completely remove and re-install Atom. This appeared when I upgraded my OS after upgrading to the latest version of Atom. Just a FYI if you see others coming here with the same issues.
